<div class="content block-collapsible-nav-content" id="block-collapsible-nav">
    <ul class="nav items" style="padding: 8px;">
        <li class="nav item current">
            <strong>Minhas Listas de Desejo</strong>
        </li>
        <li class="nav item">
            <a href="#">Ferramentas</a>
        </li>
        <li class="nav item">
            <a href="#">Eletrônicos</a>
        </li>
        <li class="nav item">
            <a href="#">Maquiagens</a>
        </li>
        <li class="nav item">
            <a href="#">Escritório</a>
        </li>
        <li class="nav item">
            <span class="delimiter"></span>
        </li>
        <li class="nav item">
            <a href="/customer/account/">Voltar</a>
        </li>
    </ul>
</div>
